version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "codecov"
  codecov:
    jobs:
      build:
        working_directory: /go/src/github.com/risoll/tokosidia
        docker:
          - image: circleci/golang:1.10.0
        environment:
          - GOCACHE: "/tmp/go/cache"
          - DEP_VERSION: 0.4.1
        steps:
          - run: git config --global url.ssh://git@github.com/risoll.insteadOf https://github.com/risoll
          - checkout
          - restore_cache:
              key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
              paths:
                  - /go/src/github.com/risoll/tokosidia/vendor
          - run:
              name: download-libraries
              command: |
                if [ ! -d /go/src/github.com/risoll/tokosidia/vendor ]; then
                    curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                    chmod +x /go/bin/dep
                    /go/bin/dep ensure
                fi
          - save_cache:
              key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
              paths:
                  - /go/src/github.com/risoll/tokosidia/vendor
          - restore_cache:
              keys:
                  - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
              paths:
                  - /tmp/go/cache
          - run:
              name: test
              command: |
                mkdir -p $GOCACHE
                go build -v
                go test -p 6 -race ./...
          - save_cache:
              key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
              paths:
                  - /tmp/go/cache
          - codecov/upload:
              file: coverage/*.json
              flags: backend,unittest